version: "3.9"
services:
  workerdisk:
    build: .
    environment:
      - API_ID=${API_ID}
      - API_HASH=${HASH}
      - TOKEN=${TOKEN}
      - DB_NAME=${DB_NAME}
      - DB_URL=${DB_URL}
      - CHANNEL=${CHANNEL}
      - ADMIN=${ADMIN}
      - LAZY_PIC=${LAZY_PIC}
    env_file:
      - ./secrets/workerdisk.env
    secrets:
      - api_credentials
      - db_credentials
    volumes:
      - workerdisk_data:/data
    ports:
      - "5000:5000"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "256M"
    read_only: true

  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    env_file:
      - ./secrets/db.env
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.stats()"]
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 10s
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
        reservations:
          cpus: "0.5"
          memory: "512M"
    read_only: true

volumes:
  workerdisk_data:
  db_data:

secrets:
  api_credentials:
    file: ./secrets/api_credentials.env
  db_credentials:
    file: ./secrets/db_credentials.env
