services:
  workerdisk:
    build: .
    environment:
      - API_ID=${API_ID}
      - API_HASH=${HASH}
      - TOKEN=${TOKEN}
      - DB_NAME=${DB_NAME}
      - DB_URL=${DB_URL}
      - CHANNEL=${CHANNEL}
      - ADMIN=${ADMIN}
      - LAZY_PIC=${LAZY_PIC}
    env_file:
      - ./secrets/workerdisk.env
    secrets:
      - api_credentials
      - db_credentials
    volumes:
      - workerdisk_data:/data
    ports:
      - "8080:5000"  # Change 5000 to 8080 if you need to expose that port
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "256M"
    read_only: true
